TOPSRCDIR = C:/Users/Geoff/Documents/GitHub/curling-g32/lib/ruby-gtk2-2.0.2
COMMAND = C:/Ruby200-x64/bin/ruby.exe C:/Users/Geoff/Documents/GitHub/curling-g32/lib/ruby-gtk2-2.0.2/exec_make.rb 
RM = rm -f
all:
install:
site-install:
clean:
distclean:
distclean: distclean-toplevel
distclean-toplevel:
	$(RM) Makefile mkmf.log
